name: Terraform Validate

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
    pull_request:
      branches: ["main"]
  
    workflow_dispatch:

jobs:
  terraform_validate:
    name: "Format and Validate Code"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.4
    
    - name: Check variables.tf
      run: |
        if [ ! -f variables.tf ]; then
          echo "variables.tf not found!"
          exit 1
        fi
        echo "variables.tf is present."

    - name: Check provider.tf
      run: |
        if [ ! -f provider.tf ]; then
          echo "provider.tf not found!"
          exit 1
        fi
        echo "provider.tf is present."
    
    - name: Check datasources.tf
      run: |
        if [ ! -f datasources.tf ]; then
          echo "datasources.tf not found!"
          exit 1
        fi
        echo "datasources.tf is present."
    
    - name: Terraform Fmt
      run: terraform fmt -check
    
    - name: Terraform Init
      run: terraform init
  
    - name: Terraform Validate
      run: terraform validate
    
    - name: Check tfplan
      run: |
        if [ ! -f tfplan ]; then
          echo "tfplan file not found!"
          exit 1
        fi
        echo "tfplan file is present."